CREATE TABLE CUSTOMER_TABLE
 (CUSTOMER_NUMBER  INTEGER, CUSTOMER_NAME VARCHAR(20), PHONE_NUMBER CHAR(8));

CREATE TABLE ORDER_TABLE
 (ORDER_NUMBER INTEGER, CUSTOMER_NUMBER INTEGER, ORDER_DATE  DATE, ORDER_TOTAL DECIMAL(10,2) );
 
CREATE TABLE STUDENT_TABLE
 (STUDENT_ID INTEGER, LAST_NAME CHAR(20), FIRST_NAME VARCHAR(12), CLASS_CODE  CHAR(2) , GRADE_PT  DECIMAL(5,2) );

CREATE TABLE COURSE_TABLE
 (COURSE_ID SMALLINT, COURSE_NAME  VARCHAR(30), CREDITS INTEGER, SEATS  INTEGER);

CREATE TABLE STUDENT_COURSE_TABLE
 (STUDENT_ID INTEGER, COURSE_ID   SMALLINT);
 
CREATE TABLE SALES_TABLE
 (PRODUCT_ID INTEGER, SALE_DATE  DATE, DAILY_SALES  DECIMAL(9,2));

CREATE TABLE EMPLOYEE_TABLE
 (EMPLOYEE_NO INTEGER, DEPT_NO SMALLINT, LAST_NAME CHAR(20), FIRST_NAME VARCHAR(12), SALARY  DECIMAL(8,2) );

CREATE TABLE DEPARTMENT_TABLE
 (DEPT_NO SMALLINT, DEPARTMENT_NAME CHAR(20), 
 MGR_NO  INTEGER, BUDGET  DECIMAL(10,2));
 
CREATE TABLE STATS_TABLE
 (COL1 SMALLINT, COL2 SMALLINT, COL3 SMALLINT, COL4 SMALLINT, 
 COL5 SMALLINT, COL6 SMALLINT);

CREATE TABLE JOB_TABLE 
 (JOB_NO INT NOT NULL UNIQUE, JOB_DESC VARCHAR(20));

CREATE TABLE EMP_JOB_TABLE
 (JOB_NO INT, EMP_NO INT);

CREATE TABLE NAMES_TABLE
 (NAME VARCHAR(30) NOT NULL UNIQUE);

CREATE TABLE HIERARCHY_TABLE 
(EMPLOYEE_NO INTEGER 
,DEPT_NO SMALLINT
,FIRST_NAME VARCHAR(12)
,LAST_NAME CHAR(20) 
,SALARY DECIMAL (10,2) 
,POSITION_NAME CHAR (20) 
,MGR_EMPLOYEE_NO INTEGER 
);

CREATE TABLE ADDRESSES
 (SUBSCRIBER_NO INTEGER, STREET VARCHAR(30), CITY VARCHAR(20), STATE CHAR(2), ZIP INTEGER, AREACODE SMALLINT, PHONE INTEGER);

CREATE  TABLE SUBSCRIBERS
 (SUBSCRIBER_NO INTEGER, MEMBER_NO SMALLINT, LAST_NAME CHAR(20), FIRST_NAME VARCHAR(20), GENDER CHAR(1), SSN INTEGER);
  
CREATE TABLE CLAIMS
 (CLAIM_ID INTEGER, CLAIM_DATE DATE, CLAIM_SERVICE SMALLINT, SUBSCRIBER_NO INTEGER, MEMBER_NO SMALLINT, CLAIM_AMT DECIMAL(12,2), PROVIDER_NO SMALLINT);

CREATE TABLE PROVIDERS
 (PROVIDER_CODE  SMALLINT, PROVIDER_NAME   VARCHAR(30), P_ADDRESS VARCHAR(30), P_CITY  VARCHAR(20), P_STATE CHAR(2), P_ZIP  INT, P_ERROR_RATE  DEC(4,4));

CREATE TABLE SERVICES
 (SERVICE_CODE  SMALLINT, SERVICE_DESC  VARCHAR(30), SERVICE_PAY  DECIMAL(7,2));

CREATE TABLE BANK_SALES 
 (PRODUCT_ID NUMBER(38,0),  PRODUCT_NAME VARCHAR(20), SALE_DATE TIMESTAMP_NTZ(6), DAILY_SALES NUMBER(15,2));

CREATE TABLE EMPLOYEE_PHONE 
 (FIRST_NAME VARCHAR(20),  LAST_NAME VARCHAR(20),  DEPT_NO NUMBER(38,0),  HOME_PHONE VARCHAR(20), WORK_PHONE VARCHAR(20),  CELL_PHONE VARCHAR(20));

CREATE TABLE LAT_LONG 
  (STATE VARCHAR(32),   LATITUDE NUMBER(11,0),   LONGITUDE NUMBER(11,0));

CREATE TABLE PIVOT_TEST_REGION_ALL 
  (REGION VARCHAR(20),   SALES_PERSON VARCHAR(30),   PRODUCT VARCHAR(20),   QUANTITY NUMBER(11,0),   COST NUMBER(10,2),   SALE_DATE DATE,   DAILY_SALES NUMBER(10,2));

CREATE TABLE SALES_SIMPLE_EXAMPLE 
  (PROD NUMBER(38,0),   TOTAL_SALES NUMBER(10,2),   REGION VARCHAR(10));

CREATE TABLE SALES_SIMPLE_EXAMPLE_UPDATED 
  (PROD NUMBER(38,0),   TOTAL_SALES NUMBER(10,2),   REGION VARCHAR(10));

CREATE TABLE STATE_GOVERNORS 
 (STATE VARCHAR(128),  GOV_FIRST_NAME VARCHAR(20),  GOV_MIDDLE_NAME VARCHAR(20),  GOV_LAST_NAME VARCHAR(20),  PARTY VARCHAR(15),  DATE_TOOK_OFFICE DATE,  YEAR_TERM_ENDS NUMBER(11,0));

CREATE TABLE WEBSITE 
  (CUSTOMER_NUMBER NUMBER(11,0),   WEB_PAGE VARCHAR(30),   CUSTOMER_TIMESTAMP TIMESTAMP_NTZ(6));