name: snowflake-devops-demo

on:
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod] # Add more environments as needed

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets['SF_' ~ matrix.env ~ '_ACCOUNT'] }}
          SF_USERNAME: ${{ secrets['SF_' ~ matrix.env ~ '_USERNAME'] }}
          SF_ROLE: ${{ secrets['SF_' ~ matrix.env ~ '_ROLE'] }}
          SF_WAREHOUSE: ${{ secrets['SF_' ~ matrix.env ~ '_WAREHOUSE'] }}
          SF_DATABASE: ${{ secrets['SF_' ~ matrix.env ~ '_DATABASE'] }}
          SNOWFLAKE_PASSWORD: ${{ secrets['SF_' ~ matrix.env ~ '_PASSWORD'] }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange

          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/ -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
